# Generated by Django 5.1 on 2024-08-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signals',
            name='check_take_profit_1',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
