# Generated by Django 5.0.7 on 2024-08-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_signals_check_take_profit_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signals',
            name='entry_point',
            field=models.FloatField(verbose_name='ТВ'),
        ),
        migrations.AlterField(
            model_name='signals',
            name='stop_loss',
            field=models.FloatField(verbose_name='СЛ'),
        ),
        migrations.AlterField(
            model_name='signals',
            name='take_profit1',
            field=models.FloatField(verbose_name='ТП1'),
        ),
        migrations.AlterField(
            model_name='signals',
            name='take_profit2',
            field=models.FloatField(verbose_name='ТП2'),
        ),
    ]
