# Generated by Django 5.0.7 on 2024-08-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_alter_signals_entry_point_alter_signals_stop_loss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttf',
            name='send_to_telegram',
            field=models.BooleanField(default=False, verbose_name='Отправка'),
        ),
    ]
