# Generated by Django 5.0.7 on 2024-08-30 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_alter_contracttf_send_to_telegram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracttf',
            options={'verbose_name': 'Контракт', 'verbose_name_plural': 'Контракты'},
        ),
        migrations.AlterModelOptions(
            name='signals',
            options={'verbose_name': 'Сигнал', 'verbose_name_plural': 'Сигналы'},
        ),
        migrations.AlterModelOptions(
            name='statistic',
            options={'verbose_name_plural': 'Статистика'},
        ),
    ]
