# Generated by Django 5.0.7 on 2024-08-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_alter_contracttf_options_alter_signals_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signals',
            name='check_take_profit_1',
            field=models.BooleanField(blank=True, default=False, verbose_name='Взятие ТП1'),
        ),
    ]
