# Generated by Django 5.0.7 on 2024-08-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_signals_activity_signals_check_take_profit_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='signals',
            name='tracking',
            field=models.BooleanField(blank=True, default=True, verbose_name='Отслеживание'),
        ),
    ]
