# Generated by Django 5.0.7 on 2024-09-01 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0010_signals_long_or_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='signals',
            name='contractTF',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trade.contracttf'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
