# Generated by Django 5.0.7 on 2024-09-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0011_signals_contracttf_delete_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttf',
            name='stop_loss',
            field=models.IntegerField(default=0, verbose_name='CЛ в %'),
        ),
    ]
