# Generated by Django 5.0.7 on 2024-09-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0012_contracttf_stop_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttf',
            name='take_profit_1',
            field=models.IntegerField(default=0, verbose_name='ТП1 в %'),
        ),
        migrations.AddField(
            model_name='contracttf',
            name='take_profit_2',
            field=models.IntegerField(default=0, verbose_name='ТП2 в %'),
        ),
    ]
