# Generated by Django 5.0.7 on 2024-09-09 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0013_contracttf_take_profit_1_contracttf_take_profit_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='signals',
            name='some_data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signals',
            name='some_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
