# Generated by Django 5.0.7 on 2024-09-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0014_signals_some_data_signals_some_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_signals_to_send', models.IntegerField(verbose_name='Количество для отправки')),
            ],
        ),
    ]
