# Generated by Django 5.0.7 on 2024-09-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0015_settingsapp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingsapp',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': 'Настройки'},
        ),
    ]
