# Generated by Django 5.0.7 on 2024-09-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0016_alter_settingsapp_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttf',
            name='signals_quantity',
            field=models.IntegerField(default=0, verbose_name='Кол.сигналов'),
        ),
    ]
