# Generated by Django 5.0.7 on 2024-09-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0017_contracttf_signals_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsapp',
            name='scanning_signals',
            field=models.BooleanField(default=False),
        ),
    ]
