# Generated by Django 5.0.7 on 2024-09-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0018_settingsapp_scanning_signals'),
    ]

    operations = [
        migrations.AddField(
            model_name='signals',
            name='checK_scan',
            field=models.BooleanField(default=False),
        ),
    ]
