# Generated by Django 5.0.7 on 2024-09-13 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0019_signals_check_scan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signals',
            old_name='checK_scan',
            new_name='check_scan',
        ),
    ]
